[package]
name = "esp8266"
version = "0.0.1"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

include = [
    "/src/**",
    "svd/esp8266.svd"
]
license = "MIT OR Apache-2.0"

[dependencies]
bare-metal = "0.2"
vcell = "0.1"
